version: '3.8'

services:
        web:
                build:
                        context: .
                ports:
                -        80:80
                volumes:
                -       ./src:/app

